# Generated by Django 2.2.3 on 2020-08-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='active_id',
            new_name='activity_id',
        ),
    ]
