# Generated by Django 2.2.3 on 2020-08-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200812_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to='blog.User'),
        ),
    ]
